<a href="https://colab.research.google.com/github/zyf13439137705-maker/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
import torch
random_tensor=torch.rand(7,7)
print(random_tensor)
# Create random tensor


tensor([[0.9274, 0.6684, 0.9454, 0.2949, 0.0362, 0.1540, 0.9795],
        [0.8160, 0.3127, 0.7604, 0.2120, 0.5131, 0.3494, 0.8050],
        [0.1820, 0.5932, 0.1209, 0.3360, 0.3880, 0.5929, 0.7423],
        [0.1788, 0.2596, 0.7267, 0.4692, 0.1064, 0.3896, 0.6017],
        [0.0923, 0.4936, 0.9590, 0.3488, 0.8178, 0.1676, 0.3188],
        [0.7216, 0.0507, 0.2736, 0.6633, 0.6335, 0.2540, 0.1181],
        [0.9258, 0.1730, 0.9979, 0.5048, 0.6381, 0.8914, 0.3001]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
result=torch.matmul(random_tensor,torch.rand(1,7).T)
print(result)
# Perform matrix multiplication


tensor([[1.7039],
        [1.7080],
        [1.4431],
        [1.2977],
        [1.4519],
        [0.9730],
        [1.9417]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)
#result=torch.matmul(torch.rand(7,7),torch.rand(1,7).T)
#print(result)

# Create two random tensors
random_tensor=torch.rand(7,7)
torch.manual_seed(0)
random_tensor2=torch.rand(1,7)
result=torch.matmul(random_tensor,random_tensor2.T)
print(result)

# Matrix multiply tensors


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print(torch.cuda.is_available())
# Create two random tensors on GPU
random1=torch.rand(2,3)
random2=torch.rand(2,3)
random1=random1.to("cuda")
random2=random2.to("cuda")
print(f"device:{random1.device}\n{random1}\n\ndevice:{random2.device}\n{random2}")


True
device:cuda:0
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

device:cuda:0
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [9]:
# Perform matmul on tensor_A and tensor_B
result=torch.matmul(random1,random2.T)
print(result)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [10]:
# Find max
print(torch.max(result))
# Find min
print(torch.min(result))

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [11]:
# Find arg max

print(torch.argmax(result))
# Find arg min
print(torch.argmin(result))

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [13]:
# Set seed
torch.manual_seed(7)


# Create random tensor
original_tensor=torch.rand(1,1,1,10)



# Remove single dimensions
squeezed_tensor=torch.squeeze(original_tensor)

# Print out tensors and their shapes
print(f"{original_tensor},{original_tensor.shape}\n{squeezed_tensor},{squeezed_tensor.shape}")


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]),torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]),torch.Size([10])
